
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ALEJA
 */
public class GaussJordan extends javax.swing.JFrame {
    int n1;
    DefaultTableModel modelo=new DefaultTableModel();
    Boolean ban= false;

    public int getN1() {
        return n1;
    }

    public void setN1(int n1) {
        this.n1 = n1;
    }
    

    /**
     * Creates new form GaussJordan
     */
    public GaussJordan() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        btngenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnresolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtprocedimiento = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gauss Jordan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 26, -1, -1));

        jButton1.setText("Ir a menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 11, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Por favor inserte el número de incógnitas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 59, -1, -1));

        txtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorActionPerformed(evt);
            }
        });
        getContentPane().add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 59, 64, -1));

        btngenerar.setText("Generar Matriz");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btngenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 90, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 131, 475, 107));

        btnresolver.setText("Resolver");
        btnresolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnresolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 249, -1, -1));

        txtprocedimiento.setColumns(20);
        txtprocedimiento.setRows(5);
        jScrollPane2.setViewportView(txtprocedimiento);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 283, 354, 225));

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 526, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dos a la N.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 540, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu a= new Menu();
    a.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorActionPerformed

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        // TODO add your handling code here:
        try {
            this.setN1(Integer.parseInt(txtvalor.getText()));
            n1 = this.getN1();
             
             if (n1<=0) {
                throw new Exception ("El valor es inválido");
            }
            Object columna[] = new Object [n1+1];  
            
            for (int i = 0; i < n1+1; i++) {
                if (i<n1) {
                    columna[i] = "X" + (i+1);
                }else{
                    columna[i] = "D";
                }
            }
            modelo = new DefaultTableModel(columna,n1);
            jTable.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btngenerarActionPerformed

    private void btnresolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresolverActionPerformed
        // TODO add your handling code here:
        try {
            int n1 = this.getN1();
            double m[][] = new double [n1][n1];
            double r[]= new double [n1];
            
            for (int i = 0; i < n1; i++) {
                for (int j = 0; j < n1; j++) {
                    m[i][j] = Double.parseDouble(String.valueOf(jTable.getValueAt(i,j)));  
                }
                r[i] = Double.parseDouble(String.valueOf(jTable.getValueAt(i,n1)));
            }
            r = this.resolver(m,r); 
            
            for (int i = 0; i < n1; i++) {
                txtprocedimiento.append("X" + (i+1) + " = " + r[i] + "\n" ); 
            }
                        
        } catch (Exception e) { 
            System.out.println(e);
        }
    }//GEN-LAST:event_btnresolverActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaussJordan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaussJordan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaussJordan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaussJordan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GaussJordan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btnresolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea txtprocedimiento;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables

    private double[] resolver(double[][] m, double[] r) {
        
        int n1 =this.getN1();
        for (int i = 0; i < 10; i++) {
            double d,c= 0;
            d = m[i][i];
            txtprocedimiento.append(Double.toString(1/d) + "*fila" + (i+1) + "\n");
            for (int j = 0; j < n1; j++) {
                m[i][j] = ((m[i][j]) / d);
            }
            r[i] = ((r[i]) /d);
            
            for (int j = 0; j < n1; j++) {
                for (int k = 0; k < n1; k++) {
                    txtprocedimiento.append(Double.toString(m[j][k]) + "\t");
                }
                txtprocedimiento.append("|\t" + Double.toString(r[j]) + "\n");
            }
            txtprocedimiento.append("\n\n");
            
            for (int x = 0; x < n1; x++) {
                if (i != x) {
                    c = m[x][i];
                    txtprocedimiento.append("-" +Double.toString (c) + " *fila " +(i+1) + "+ fila" + (x+1) + "\n");
                    for (int y = 0; y < n1; y++) {
                        m[x][y] = m[x][y] - c * m[i][y];
                    }
                    r[x] = r[x] - c * r[i];
                    
                    for (int j = 0; j < n1; j++) {
                        for (int k = 0; k < n1; k++) {
                            txtprocedimiento.append(Double.toString (m[j][k])+ "\t"); 
                        }
                        txtprocedimiento.append("|\t" + Double.toString(r[j])+ "\n");
                    }
                    txtprocedimiento.append("\n\n");
                }
            }
        }
        return r;
    }
}
